site_name: DMC Extensibility Bootcamp
site_url: ""
repo_url: "https://github.com/SAP-samples/digital-manufacturing-extension-samples"

theme:
    name: null
    custom_dir: 'docs/theme/material'
    logo: 'assets/logo_sap.jpeg'
    favicon: assets/favicon.png
    language: 'en'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    feature:
        tabs: true
    palette:
        primary: 'black'
        accent: 'blue'
extra_css:
    - 'theme/stylesheets/extra.css'

nav:
    - Unit 1: 
        -  'Overview': 'index.md'
        -  'BTP Extension Suite': 'BTPExtensionSuite.md'
        -  'DMC Use Cases': 'DMCUseCases.md'
        -  'Bootcamp Scenario': 'BootcampUseCase.md'
    - Unit 2: 
        -  'Content': 'Field&IntegrationExtensions.md'
    - Unit 3: 
        -  'Content': 'InAppExtensions.md'
    - Exercise 1:
        -  'Exercise 1.1': 'Exercise1.1.md'
        -  'Exercise 1.2': 'Exercise1.2.md'
    - FAQ: 
        -  'Content': 'FAQ.md'
    - Participant Guide: 
        -  'Content': 'ParticipantGuide.md'

markdown_extensions:
    - attr_list
    - admonition             # block-styled content like "!!! note"
    - footnotes              # footnotes; references with [^1] inline and decl's with [^1]: Lorem ipsum, ...
    - toc:
        permalink: True 